connect-foundation/2019-07

client/.eslintrc.js, client/package-lock.json, client/package.json, client/yarn.lock, server/.eslintrc.js, server/package-lock.json, server/package.json
1. !HOTFIX: yarn 의존성 오류 제거
2. eslint:recommended 적용
3. client, server 전부 npm start로 동작 확인
1. eslint에서 plugin, extends로 airbnb와 react를 설정하면 오류가 발생. 
- 이를 해결하면, 해결 내용만 담긴 PR을 날릴 예정임.
=> Feat: eslint 설정

server/.eslintrc.js, server/app.js, server/bin/www, server/routes/index.js
- server 디렉토리에 airbnb lint 적용
- server 디렉토리에 airbnb lint가 적용되지 않은 채 merge되었던 문제
#1
- 조찬기
=> Style: server 디렉토리에 airbnb lint 적용

client/package.json, client/src/Router.js, client/src/components/inGame/PlayerFooter.js, client/src/components/inGame/ProgressBar.js, client/src/pages/MainPage.js, client/src/pages/host/WaitingRoom.js, client/src/pages/mainPage/EnterNickname.js, client/src/pages/mainPage/EnterRoomNumber.js, client/src/pages/player/WaitingRoom.js, server/app.js, server/bin/www, server/package.json, server/socket.js, server/yarn.lock
1. Host 게임 대기실 페이지 소켓 통신 구현
- 방은 하나만 존재한다고 가정하고 구현하여 모든 Player는 같은 방으로 입장함
2. Player 게임 대기실 페이지 소켓 통신 구현
#3 #6
짝코더: 오창영
=> Feat: 게임 대기실 Player/Host 소켓 통신 구현 완료

client/src/components/common/Buttons.js, client/src/components/common/MainContainer.js, client/src/components/logo/Logo.css, client/src/index.css, client/src/pages/host/WaitingRoom.js, client/src/pages/mainPage/EnterNickname.js, client/src/pages/mainPage/EnterRoomNumber.js, client/src/styles/common.js
1. 메인 페이지가 모바일에서 꽉차게 보이지 않는 문제 수정
2. 메인 페이지의 푸터가 모바일에서 너무 붙어서 보이는 문제 수정
=> Design: 모바일 퍼스트형 디자인 반영 및 버튼 기본 스타일 변경

README.md
README.md 문서에 내용을 추가했습니다.
- all-contributors 등을 이용해 README 꾸미기
=> Docs: 프로젝트 소개 README.md 추가

client/package.json, client/src/components/common/Buttons.js, client/src/components/mainPage/EnterNickname.js, client/src/components/mainPage/EnterRoomNumber.js, client/src/index.css, client/src/pages/host/WaitingRoom.js
1. customu 오타를 custom으로 수정
2. 버튼의 재사용성을 고려한 리팩토링
=> Refactor: 버튼의 오타 수정과 재사용성 고려한 리팩토링

client/src/components/mainPage/EnterNickname.js, server/models/inMemory.js, server/routes/apis/room.js
- inMemory.rooms가 있으므로 getRooms를 삭제하고 getRoom을 통해 api에서 유효성 처리
=> Style: 인메모리 관련 메서드 삭제

client/src/components/detailRoom/RoomInformation.js, client/src/components/detailRoom/TabContents.js, client/src/pages/host/HostDetailRoom.js
- 프론트 기본 동작 구현
- Modal 컴포넌트화가 진행 중이어서 Modal이 생성 구현은 미구현
- 데이터베이스 및 백엔드가 미구현되어 fetch와 관련된 구현은 미구현
#35 
원활한 소켓 통신을 위해 기존 디자인에서 한번 사양이 변경되었음. 자세한 사항은 관련 이슈 참고.
=> Feat: 단일 방 상세 페이지 프론트 기본 동작 구현

client/src/components/common/FlexibleInput.js
- maxLength를 초과할 경우 input 막음
- focus하면 입력 가능한 length가 오른쪽에 출력
- 글자수가 0일때 placeholder 출력
=> Feat: 글자수에 따라 높이가 달라지는 Input 제작

README.md
?: 데일리 스크럼 링크가 직관적이지 않아 수정.
각 주차별 데일리 스크럼 링크 추가.
프로젝트 배포 링크 오류 수정.
=> Docs(README): 데일리 스크럼 상세 링크 추가

client/src/components/common/LoadingCircle.js, client/src/components/inGame/Hourglass.js, client/src/components/inGame/PlayerWaiting.js
인게임에 필요한 컴포넌트를 추가하였습니다.
- Hourglass: 퀴즈의 남은 시간을 직관적으로 알려주는 컴포넌트
- LoadingCircle: 로딩중임을 알려주는 컴포넌트 
- PlayerWaiting에서 로딩 이미지를 LoadingCircle 컴포넌트로 교체
=> [PR] Feat: 인게임 리팩토링에 필요한 컴포넌트 추가

client/src/components/common/FlexibleInput.js
- 한글 입력에 대한 입력 제한 
- 복사 붙여넣기에 대한 입력 제한
뭔가 마음에 안드는 방법이지만 입력 제한은 잘 동작합니다..
다른 방법이 있을 것 같다면 알려주세요..!
=> Fix: 한글, 복사 붙여넣기에 대해 입력 제한이 안되는 현상 수정

client/src/constants/apiAddresses.js, client/src/pages/host/SelectRoom.js, client/src/utils/fetch.js, server/models/database/tables/Room.js, server/routes/api.js, server/routes/apis/user.js
- 방 만들기를 눌렀을 때, Modal을 출력하고 유저에게 입력받은 input값과 동일한 방을 생성
- 방 만들기를 통해 입력받은 값이 26글자 이내인지 확인
- User 내에서 중복되지 않는 이름인지 확인 (client만)
> server 측은 하나의 쿼리로 막는 것이 어려우므로 Database에서 `user_id + title`에 대한 unique 추가가 필요함 
#33 #34
=> Feat: 방 list 페이지 구현

server/models/database/tables/Item.js, server/models/database/tables/Quizset.js, server/models/rooms.js
다른 이름을 사용해 예약어와 겹치는 문제 해결
#166
=> Fix: DB 테이블 칼럼에서 order명 변경

client/src/components/common/Loading.js, client/src/utils/caseChanger.js
```javascript
function parseCamelObject(object, option) {
return parseObjectFunction(object, parseCamelString, option);
}
function parseSnakeObject(object, option) {
return parseObjectFunction(object, parseSnakeString, option);
}
option = {
canStringValueChange : true
}
```
canStringValueChange 
- key가 아닌 stringValue도 case를 변환하는 옵션.
- default는 true
- object의 key만을 변경하고자 할 때는 false를 주어야 함.
```javascript
const testData = [
{
id: 1,
image_path: null,
items: [
{ id: 1, is_answer: 1, order: 0, quiz_id: 1, title___: "test_title" },
{ id: 2, is_answer: 1, order: 0, quiz_id: 1, title: "밥" },
],
time_limit: 30,
},
];
console.log(
parseCamelObject(testData[0], {
canStringValueChange: true,
}),
parseCamelObject(testData[0], {
canStringValueChange: false,
}),
);
// result
// canStringValueChange: …
```
=> Feat: camelCase <-> snake_case 변환하는 메소드 구현

client/src/components/inGame/HostLoading.js, client/src/components/inGame/HostPlaying.js, client/src/components/inGame/HostQuizPlayingRoom.js, client/src/components/inGame/HostResult.js, client/src/components/inGame/HostSubResult.js, client/src/components/inGame/HostWaitingRoom.js, client/src/pages/host/HostGameRoom.js, client/src/reducer/hostGameReducer.js
- Host 인게임 페이지 리팩토링
- Player가 없을 때 퀴즈를 시작할 수 없도록 하는 기능 추가
- 맨 마지막 퀴즈의 결과일 때 `최종결과` 버튼이 출력되도록 기능 추가
- `n명이 풀이 중` 문구를 `n명이 참가 중`으로 문구 수정
#176
=> Feat: Host 인게임 페이지 리팩토링 및 UX 적 기능 추가

client/src/components/detailRoom/QuizTab.js, client/src/components/detailRoom/TabContents.js, client/src/components/edit/ImageField.js, client/src/components/edit/Item.js, client/src/components/edit/SaveButton.js, client/src/components/edit/Section.js, client/src/components/edit/SideBar.js, client/src/components/edit/Thumbnail.js, client/src/components/edit/Title.js, client/src/pages/host/EditPage.js, client/src/pages/host/HostDetailRoom.js, client/src/reducer/hostEditReducer.js
너무 큰 기능이 추가되었습니다.
바로 merge하고 테스트해보면서 의견을 남겨주시면 좋을 거 같습니다.
=> Feat: EditPage API와 연결되는 프론트 구현

client/src/components/inGame/PlayerQuiz.js, server/models/database/tables/Quizset.js, server/models/rooms.js
**퀴즈 이미지 추가**
퀴즈에서 이미지가 보이도록 추가.
이미지 정보가 없는 경우 이미지를 보이지 않음
**퀴스 세트 생성 로직 변경**
quizset 생성 시, 유연하게 대처하기 위함.
=> [PR] Feat: 퀴즈 이미지 추가

client/src/components/common/ScoreChart.js, client/src/components/inGame/HostQuizPlayingRoom.js
- 문항 중 title이 없는 문항은 출력하지 않도록 수정함
=> !HOTFIX: 문항 수가 4개가 아닐 때 4개로 출력되는 현상 수정

client/src/components/inGame/PlayerQuiz.js
퀴즈 item에서 유효한 item만 렌더링 하도록 변경
=> [PR] !HOTFIX: 문항 수가 4개가 아닐 때 4개로 출력되는 현상 수정

client/src/components/common/FlexibleInput.js, client/src/components/common/Loading.js, client/src/components/common/Modal.js, client/src/components/common/ModalProvider.js, client/src/components/inGame/HostLoading.js, client/src/components/inGame/HostResult.js, client/src/components/inGame/HostWaitingRoom.js, client/src/components/mainPage/EnterNickname.js, client/src/pages/host/HostGameRoom.js
- Modal의 Flexible Input에서 이전에 저장되었던 값이 그대로 저장되는 이슈 수정
- 이슈를 수정하면서 Flexible Input의 max input 값을 검사하는 로직을 리팩토링 하였습니다.
- Flexible Input이 Blur 되었을 때 설정된 Focus가 아웃되지 않는 현상 수정
- Modal StopPropagation을 preventDefault 방식으로 변경
- Host Waiting Room에서 로딩 글씨가 겹치는 현상 수정
- Host Game 페이지에서 useEffect 의존성 추가
- Host 최종 결과 페이지에서 창이 작아지면 나가기 버튼이 클릭되지 않는 현상 수정
- 닉네임을 빠르게 입력하거나, 복사 붙여넣기 시에 유효하지 않은 값이 서버로 전송되는 현상 수정
#229  #232 #235
=> Fix: Modal Flexible Input 이전 값이 그대로 저장되어 있는 이슈 수정 외 리팩토링

client/src/utils/fetch.js, server/app.js, server/models/database/tables/Quizset.js, server/models/rooms.js, server/routes/api.js, server/routes/apis/game.js, server/routes/apis/login.js, server/routes/apis/room.js, server/routes/apis/user.js
backend api 주소 호출시 맨 앞에 /api/ 주소를 추가
이에 따라 주석에 적혀있는 api 주소또한 변경 & 리펙토링
퀴즈 세트 객체 생성지 quiz_order 순으로 생성하도록 변경
=> [PR] Fix: nginx proxy 설정을 위한 api 호출 주소 변경

client/src/components/common/FlexibleInput.js
- Flexible Input이 정상 동작하도록 수정하였습니다.  😥
#239
=> !HOTFIX: Flexible Input 새로운 입력이 안먹히는 이슈 수정

client/src/components/common/CopyrightFooter.js, client/src/components/detailRoom/QuizTab.js, client/src/components/edit/SaveButton.js, client/src/pages/host/HostDetailRoom.js, client/src/pages/host/SelectRoom.js, client/src/pages/login/CallBackPage.js
- 뒤로가기에 대해 좀 더 자연스럽게 동작하도록 변경
- 메인 페이지의 푸터 메시지 변경
- 방 상세 페이지에서 퀴즈 리스트 로딩 시 로딩 창이 뜨도록 변경
특이사항: 다함께 페어 프로그래밍!
=> Feat: 퀴즈 데이터를 불러올 때 Loading 창이 뜨도록 기능 추가 외

client/src/components/inGame/HostResult.js, client/src/components/mainPage/EnterRoomNumber.js, client/src/pages/login/CallBackPage.js
- Host 최종 결과 이후 뒤로가기 시 게임이 다시 시작되는 오류
- Android 웹에서 방번호 입력 시 Toast 메시지가 발생하는 이슈
- 간헐적으로 로그인 Callback 페이지에서 넘어가지 않는 현상
- 확실히 고쳐진건지 잘 모르겠습니다 ㅠ_ㅠ
=> [PR] !HOTFIX 버그 수정

client/src/components/edit/SideBar.js, client/src/components/inGame/Layout.js
- 퀴즈 편집 페이지의 퀴즈 추가, 퀴즈 삭제 버튼 글자 크기 확대, 글자 그림자 제거
- 인게임 퀴즈 타이틀 글자 크기 확대
=> [PR] 모바일 환경에서 잘 안보이는 글자 크기 확대

client/src/components/detailRoom/QuizTab.js, client/src/pages/login/CallBackPage.js
- 퀴즈가 없을 때 퀴즈 생성이 안되는 문제 수정
- 로그인 callback에서 안넘어가는 현상 대응을 위한 메시지 추가
=> !HOTFIX: 퀴즈가 없을 때 퀴즈 생성이 안되는 문제 수정
